<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Authors>George Koukoudis</Authors>
    <Company>GrKouk</Company>
    <Copyright>George Koukoudis</Copyright>
    <Version>3.0.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GrKouk.Erp.Definitions\GrKouk.Erp.Definitions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="CashDiary\" />
  </ItemGroup>

</Project>
