<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Authors>George Koukoudis</Authors>
    <Company>GrKouk</Company>
    <Copyright>George Koukoudis</Copyright>
    <PackageVersion>3.0.0.0</PackageVersion>
    <Title>GrKouk.Erp.Definitions</Title>
    <Description>GrKouk.Erp.Definitions </Description>
    <AssemblyVersion>3.0.0.0</AssemblyVersion>
    <FileVersion>3.0.0.0</FileVersion>
    <Version>3.0.0.0</Version>
  </PropertyGroup>

</Project>
