<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <UserSecretsId>aspnet-GrKouk.Web.ERP-9809E9E6-BFCC-497C-AA52-99A71FFC0427</UserSecretsId>
    <Authors>George Koukoudis</Authors>
    <Company>GrKoukOrg</Company>
    <Copyright>GrKoukOrg</Copyright>
    <Version>2.2.1.2</Version>
    <PackageVersion>$(Version)</PackageVersion>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <FileVersion>$(Version)</FileVersion>
    <Title>GrKoukOrg Erp</Title>
  </PropertyGroup>

 
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.0" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="9.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="9.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="9.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="9.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="9.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.0" />
    <PackageReference Include="NToastNotify" Version="8.0.0" />
    <PackageReference Include="QuestPDF" Version="2025.4.0" />
    <PackageReference Include="Syncfusion.EJ2.AspNet.Core" Version="31.1.21" />
    <PackageReference Include="Syncfusion.Pdf.Net.Core" Version="31.1.21" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GrKouk.Erp.Definitions\GrKouk.Erp.Definitions.csproj" />
    <ProjectReference Include="..\GrKouk.Erp.Domain\GrKouk.Erp.Domain.csproj" />
    <ProjectReference Include="..\GrKouk.Erp.Dtos\GrKouk.Erp.Dtos.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove=".eslintrc.json" />
    <Content Remove="package.json" />
    <Content Remove="Pages\_MainInfo.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <None Include=".eslintrc.json" />
    <None Include="package.json" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Pages\Components\" />
    <Folder Include="Pages\Configuration\CashFlow\CFADocTypeDefs\" />
    <Folder Include="wwwroot\lib\bootstrap5" />
    <Folder Include="wwwroot\productimages\" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="Pages\CommonEntities\Warehouses\Create.cshtml" />
    <AdditionalFiles Include="Pages\CommonEntities\Warehouses\Edit.cshtml" />
    <AdditionalFiles Include="Pages\CommonEntities\Warehouses\Index.cshtml" />
    <AdditionalFiles Include="Pages\Shared\_DeleteConfirmationPartial.cshtml" />
    <AdditionalFiles Include="Pages\Sync\Logging\Index.cshtml" />
    <AdditionalFiles Include="Pages\Sync\SyncBuyDocs\Index.cshtml" />
  </ItemGroup>

  

</Project>
